# Common configuration for the services

# Application specific configuration
microshop:
  accessLog.threshold: 0
  methodTracing.enabled: true

management:
  endpoints:
    web:
      exposure:
        # Spring Boot Admin uses several Actuator endpoints
        include: "*"

# Each microservice uses its own session cookie name to prevent conflicts
server.servlet.session.cookie.name: JSESSIONID_${spring.application.name}

spring:
  cloud:
    config:
      # Allow local configuration such as system properties, to override the server config, convenient for server.port
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    # To use the Zipkin server without the service registry
#    base-url: http://localhost:9411/
    # To use the Zipkin server with the service registry
    base-url: http://zipkin/

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level:
  ROOT: INFO
  #org.springframework: DEBUG
  #org.springframework.cloud: DEBUG
  #com.netflix: DEBUG
  #com.netflix.hystrix: DEBUG
  #com.adeliosys: DEBUG
