# Common configuration for the services

management:
  endpoints:
    web:
      exposure:
        # Change web exposed Actuators as needed, default value is: health,info
        include: health,info

logging.level:
  ROOT: INFO
  #org.springframework: DEBUG
  #org.springframework.cloud: DEBUG
  #com.netflix: DEBUG
  #com.netflix.hystrix: DEBUG
  #com.adeliosys: DEBUG
