# Common configuration for the services

# Application specific configuration
microshop:
  accessLog.threshold: 0
  methodTracing.enabled: true

management:
  endpoints:
    web:
      exposure:
        # Spring Boot Admin uses several Actuator endpoints
        include: "*"

# Each microservice uses its own session cookie name to prevent conflicts
server.servlet.session.cookie.name: JSESSIONID_${spring.application.name}

spring:
  cloud:
    config:
      # Allow local configuration such as system properties, to override the server config, convenient for server.port
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    # Uncomment to use the Zipkin server without the service registry
#    base-url: http://localhost:9411/
    # Uncomment to use the Zipkin server with the service registry
    base-url: http://zipkin/
    # Uncomment to disable Zipkin
#    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  # Default pattern sample output: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
  # Sample output: 2019-08-24 13:17:13.031  INFO 34200 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
  # Shorter (by 23 chars) custom pattern (removed date, removed PID, removed triple dash, removed colon), uncomment if needed :
  pattern.console: ${CONSOLE_LOG_PATTERN:%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
  # Sample output: 14:42:56.692  INFO [           main] o.apache.catalina.core.StandardService   Starting service [Tomcat]
  # Even shorter custom pattern (same as previous, removed thread, shortened the logger name), uncomment if needed
  #  pattern.console: ${CONSOLE_LOG_PATTERN:%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-20.20logger{19}){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
  # Sample output: 14:45:24.632  INFO .c.c.StandardService Starting service [Tomcat]
  level:
    ROOT: INFO
#    org.springframework: DEBUG
#    org.springframework.cloud: DEBUG
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
