# Common configuration for the services

# Application specific configuration
app:
  accessLog:
    threshold: 0

management:
  endpoints:
    web:
      exposure:
        # Spring Boot Admin uses several Actuator endpoints
        include: "*"

# Each microservice uses its own session cookie name to prevent conflicts
server.servlet.session.cookie.name: JSESSIONID_${spring.application.name}

spring:
  cloud:
    config:
      # Allow local configuration such as system properties, to override the server config, convenient for server.port
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true

# Registry client configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level:
  ROOT: INFO
  #org.springframework: DEBUG
  #org.springframework.cloud: DEBUG
  #com.netflix: DEBUG
  #com.netflix.hystrix: DEBUG
  #com.adeliosys: DEBUG
