server.port: 8080

# Gateway configuration
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # Eureka returns upper case service IDs by default
          lowerCaseServiceId: true
      routes:
        - id: orders-route
          uri: lb://order/
          predicates:
            - Path=/api/orders/**
        - id: articles-route
          uri: lb://stock/
          predicates:
            - Path=/api/articles/**

logging:
  level:
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: WARN
