server.port: 8080

# Gateway configuration
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # Eureka returns upper case service IDs by default
          lowerCaseServiceId: true
