server.port: 8082

spring:
  # Uncomment to use a file based DB instead of the default "jdbc:h2:mem:testdb" in-memory DB
  #datasource.url: jdbc:h2:file:~/data/h2/microshop-order
  # Uncomment to add logging
  #datasource.url: jdbc:h2:mem:testdb;TRACE_LEVEL_FILE=4
  h2.console.enabled: true
  jpa:
    open-in-view: true
