server.port: 8082

spring:
  application.name: microshop-order
  #datasource.url: jdbc:h2:mem:microshop-order
  #datasource.url: jdbc:h2:file:~/data/h2/microshop-order
  main.banner-mode: "off"
  h2.console.enabled: true
  jpa:
    open-in-view: true

logging.level:
  ROOT: INFO
  #org.springframework: INFO
  #com.adeliosys: DEBUG
