server.port: 8888

app:
  accessLog:
    threshold: 0

spring:
  application.name: config
  main.banner-mode: "off"
  profiles:
    # The "native" profile allows local configuration files for the config server
    active: native
  cloud.config.server:
    # Uncomment to change the URL prefix of the config server, for example if embedded with the services registry
    #prefix: /config
    native.search-locations:
      - file:./services-config
      - classpath:/services-config

logging:
  # Default pattern sample output: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
  # Sample output: 2019-08-24 13:17:13.031  INFO 34200 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
  # Shorter (by 23 chars) custom pattern (removed date, removed PID, removed triple dash, removed colon), uncomment if needed :
  pattern.console: ${CONSOLE_LOG_PATTERN:%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
  # Sample output: 14:42:56.692  INFO [           main] o.apache.catalina.core.StandardService   Starting service [Tomcat]
  # Even shorter custom pattern (same as previous, removed thread, shortened the logger name), uncomment if needed
  #  pattern.console: ${CONSOLE_LOG_PATTERN:%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-20.20logger{19}){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
  # Sample output: 14:45:24.632  INFO .c.c.StandardService Starting service [Tomcat]
  level:
    ROOT: INFO
#    org.springframework: DEBUG
#    org.springframework.cloud: DEBUG
    org.springframework.cloud.config.server.environment.NativeEnvironmentRepository: WARN
